main/urls.py
from django.contrib import admin
from django.urls import path, include

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'index'),
    path('about/', views.about, name = 'about'),
    path('auth/', include('authentication.urls')),
    path('shop/', include('shop.urls')),

]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from shop import views
from shop.views import ProductsListView, ProductsDetailView

urlpatterns = [
    path('fill-database/', views.fill_database, name='fill_database'),
    path('', ProductsListView.as_view(), name='shop'),
    path('cart_view/', views.cart_view, name='cart_view'),
    path('detail/<int:pk>/',
         ProductsDetailView.as_view(),
         name='shop_detail'),
    path('add-item-to-cart/<int:pk>', views.add_item_to_cart,
         name='add_item_to_cart'),
    path('delete_item/<int:pk>', views.CartDeleteItem.as_view(),
         name='cart_delete_item'),
    path('make-order/', views.make_order, name='make_order'),
]

shop/models.py
from decimal import Decimal

from django.contrib.auth.models import User
from django.db import models, transaction
from django.db.models import Sum
from django.db.models.signals import post_save,\
    post_delete
from django.dispatch import receiver
from django.utils import timezone


class Product(models.Model):
    name = models.CharField(max_length=255,
                            verbose_name='Наименование продукта')
    code = models.CharField(max_length=255,
                            verbose_name='Код продукта')
    price = models.DecimalField(max_digits=20,
                                decimal_places=2)
    unit = models.CharField(max_length=255,
                            blank=True, null=True)
    image_url = models.URLField(blank=True, null=True)
    note = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.name} - {self.price}'


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=20, decimal_places=2,
                                 blank=True, null=True)
    time = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.user} - {self.amount}'

    @staticmethod
    def get_balance(user: User):
        amount = Payment.objects.filter(user=user).aggregate(
                  Sum('amount'))['amount__sum']
        return amount or Decimal(0)


class Order(models.Model):
    STATUS_CART = '1_cart'
    STATUS_WAITING_FOR_PAYMENT = '2_waiting_for_payment'
    STATUS_PAID = '3_paid'
    STATUS_CHOICES = [
        (STATUS_CART, 'cart'),
        (STATUS_WAITING_FOR_PAYMENT, 'waiting_for_payment'),
        (STATUS_PAID, 'paid')
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=32, choices=STATUS_CHOICES,
                              default=STATUS_CART)
    amount = models.DecimalField(max_digits=20, decimal_places=2,
                                 blank=True, null=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    payment = models.ForeignKey(Payment, on_delete=models.PROTECT,
                                blank=True, null=True)
    comment = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.user} - {self.amount} - {self.status}'

    @staticmethod
    def get_cart(user: User):
        cart = Order.objects.filter(user=user,
                                    status=Order.STATUS_CART
                                    ).first()
        if cart and (timezone.now() - cart.creation_time).days > 7:
            cart.delete()
            cart = None
        if not cart:
            cart = Order.objects.create(user=user,
                                        status=Order.STATUS_CART,
                                        amount=0)
        return cart

    def get_amount(self):
        amount = Decimal(0)
        for item in self.orderitem_set.all():
            amount += item.amount
        return amount

    def make_order(self):
        items = self.orderitem_set.all()
        if items and self.status == Order.STATUS_CART:
            self.status = Order.STATUS_WAITING_FOR_PAYMENT
            self.save()
            auto_payment_unpaid_orders(self.user)

    @staticmethod
    def get_amount_of_unpaid_orders(user: User):
        amount = Order.objects.filter(user=user,
                                      status=Order.STATUS_WAITING_FOR_PAYMENT,
                                      ).aggregate(Sum('amount'))['amount__sum']
        return amount or Decimal(0)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    discount = models.DecimalField(max_digits=20, decimal_places=2, default=0)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.product} - {self.price}'

    @property
    def amount(self):
        return self.quantity * (self.price - self.discount)


@transaction.atomic()
def auto_payment_unpaid_orders(user: User):
    unpaid_orders = Order.objects.filter(
        user=user, status=Order.STATUS_WAITING_FOR_PAYMENT)
    for order in unpaid_orders:
        if Payment.get_balance(user) < order.amount:
            break
        order.payment = Payment.objects.all().last()
        order.status = Order.STATUS_PAID
        order.save()
        Payment.objects.create(user=user, amount=order.amount)


@receiver(post_save, sender=OrderItem)
def recalculate_order_amount_after_save(
        sender, instance, **kwargs):  # instance это OrderItem
    order = instance.order
    order.amount = order.get_amount()
    order.save()


@receiver(post_delete, sender=OrderItem)
def recalculate_order_amount_after_delete(
        sender, instance, **kwargs):  # instance это OrderItem
    order = instance.order
    order.amount = order.get_amount()
    order.save()


@receiver(post_save, sender=Payment)
def auto_payment(sender, instance, **kwargs):  # instance это OrderItem
    user = instance.user
    auto_payment_unpaid_orders(user)

shop/forms.py
from django import forms

from shop.models import OrderItem


class AddQuantityForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['quantity']

shop/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator

from django.views.generic import ListView, DetailView, DeleteView

from shop.forms import AddQuantityForm
from shop.models import Product, Order, OrderItem
from shop.scraping import array, ScrapingError


def fill_database(request):
    if request.method == "POST" and request.user.is_staff:
        try:
            array()
        except ScrapingError as err:
            print(str(err))
            return render(request, "shop/fill-products.html",
                          {"message": str(err)})

    return render(request, "shop/fill-products.html", {"message": None})


class ProductsListView(ListView):
    model = Product
    template_name = 'shop/shop.html'


class ProductsDetailView(DetailView):
    model = Product
    template_name = 'shop/shop-details.html'


@login_required(login_url=reverse_lazy('login'))
def add_item_to_cart(request, pk):
    if request.method == 'POST':
        quantity_form = AddQuantityForm(request.POST)
        if quantity_form.is_valid():
            quantity = quantity_form.cleaned_data['quantity']
            if quantity:
                cart = Order.get_cart(request.user)
                # product = Product.objects.get(pk=pk)
                product = get_object_or_404(Product, pk=pk)
                cart.orderitem_set.create(product=product,
                                          quantity=quantity,
                                          price=product.price)
                cart.save()
                return redirect('cart_view')
        else:
            pass
    return redirect('shop')


@login_required(login_url=reverse_lazy('login'))
def cart_view(request):
    cart = Order.get_cart(request.user)
    items = cart.orderitem_set.all()
    context = {
        'cart': cart,
        'items': items,
    }
    return render(request, 'shop/cart.html', context)


@method_decorator(login_required, name='dispatch')
class CartDeleteItem(DeleteView):
    model = OrderItem
    template_name = 'shop/cart.html'
    success_url = reverse_lazy('cart_view')

    # Проверка доступа
    def get_queryset(self):
        qs = super().get_queryset()
        qs.filter(order__user=self.request.user)
        return qs


@login_required(login_url=reverse_lazy('login'))
def make_order(request):
    cart = Order.get_cart(request.user)
    cart.make_order()
    return redirect('shop')

templates/shop/cart.html
{% extends 'base-page.html' %}
{% load static %}

{% block title %}
  Fill Products
{% endblock title %}

{% block container %}

{% for item in items %}

    <table class="table">
        <tr>
            <th>Product Name</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
            <th>Action</th>
        </tr>
        <tr>
            <th>{{ item.product }}</th>
            <th>{{ item.quantity }}</th>
            <th>{{ item.price }}</th>
            <th>{{ item.amount }}</th>
            <th>
                <div class="col-12 col-md-1 item">
                    <form method="post" action="{% url 'cart_delete_item' item.pk %}">
                        {% csrf_token %}
                        <button type="submit" style="color: green"><u>delete</u></button>
                    </form>
                </div>
            </th>
        </tr>

    </table>

{% endfor %}

<hr class="hr"/>
<div class="row" >
    <div class="col-12 col-md-7 item"></div>
    <div class="col-12 col-md-2 item">Total amount</div>
    <div class="col-12 col-md-2 item">{{ cart.amount }}</div>
</div>
<hr class="hr"/>

<div class="row" >
    <div class="col-12 col-md-7 item"></div>
    <div class="col-12 col-md-2 item">
        <a class="contactus-bar-btn f_right" href="{% url 'make_order' %}">
            Process to Payment
        </a>
    </div>
</div>
{% endblock container %}

templates/shop/fill-products.html
{% extends 'base-page.html' %}
{% load static %}

{% block title %}
  Fill Products
{% endblock title %}

{% block container %}

<div class="main-content-wrapper">
  <section class="breadcrumb-section about">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-lg-5">
          <div class="breadcrumb-wrapper">
            <h2>Filling Products for Shop</h2>
            <form method="post" action="{% url 'fill_database' %}">
              {% csrf_token %}
              <button class="learn-more-btn" name="fill_database" type="submit" onclick="runSpinner()">
                <span class="spinner spinner-border spinner-border-sm" role="status" id="spinner"
                    style="visibility: hidden" aria-hidden=""true></span>
                run scraping for fill database
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>

  {% if message %}
    <div class="container">
      <div class="row">
        <div class="main-heading-block">
          <h2>Errors of scrapung: <br><br>
            <span style="color:red">{{message}}</span>
          </h2>
        </div>
      </div>
    </div>
  {% endif %}
</div>
<br><br><br>

{% endblock container %}

templates/shop/shop-details.html
<div class="col-lg-4 col-md-6 mb-4">
            <div class="card" style="width: 18rem;">
                <form action="post" action="">
                   <a href="#"><img style="width: 18rem" class="card-img-top img-fluid" src="{{product.image_url}}" alt=""></a>

                    <div class="card-body">
                        <h4 class="card-title"><b>{{ product.name}}</b></h4>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"></li>
                        <li class="list-group-item">Price: {{ product.price }}</li>
                        <li class="list-group-item">
                            <label for="id_quantity" class="form-label">Quantity: </label>
                            <Input style="width:100px" type="number" name="quantity" value="1"
                                   min="1" required id="id_quantity">
                        </li>
                        <li class="list-group-item"></li>
                    </ul>
                    <div class="card-body">
                        <button class="learn-more-btn" type="submit">buy now</button>
                        <a href="{% url 'shop' %}" class="contactus-bar-btn f_right">return</a>
                        <br><br>
                    </div>
                </form>
            </div>
        </div>

templates/shop/shop.html
{% extends 'base-page.html' %}
{% load static %}

{% block title %}
  Shop
{% endblock title %}

{% block container %}
<!--<div class="gtco-section border-bottom animate-box fadeInUp animated-fast">-->

{% for product in object_list %}
    <div class="col-lg-4 col-md-6 mb-4">
        <div class="card" style="width: 18rem;">
            <form method="post" action="{% url 'add_item_to_cart' product.pk %}">
                {% csrf_token %}
               <a href="#"><img style="width: 18rem" class="card-img-top img-fluid" src="{{product.image_url}}" alt=""></a>

                <div class="card-body">
                    <h4 class="card-title"><b>{{ product.name}}</b></h4>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"></li>
                    <li class="list-group-item">Price: {{ product.price }}</li>
                    <li class="list-group-item">
                        <label for="id_quantity" class="form-label">Quantity: </label>
                        <Input style="width:100px" type="number" name="quantity" value="1"
                               min="1" required id="id_quantity">
                    </li>
                    <li class="list-group-item"></li>
                </ul>
                <div class="card-body">
                    <button class="learn-more-btn" type="submit">buy now</button>
                    <a href="{% url 'shop_detail' product.pk %}" class="contactus-bar-btn f_right">detail</a>
                    <br><br>
                </div>
            </form>
        </div>
    </div>

{% endfor %}

<!--</div>-->
{% endblock container %}